VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  (1..3).each do |i|
    config.vm.define "okd-node#{i}" do |node|
      node.vm.box = "generic/ubuntu2204"
      node.vm.hostname = "okd-node#{i}"
      node.vm.network "private_network", type: "dhcp"
      node.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = 2
      end
      node.vm.provision "shell", path: "bootstrap.sh"
    end
  end
end